# Generated by Django 2.2.3 on 2019-08-09 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capchine', '0003_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='u',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roly', to=settings.AUTH_USER_MODEL),
        ),
    ]
