# Generated by Django 2.2.3 on 2019-08-09 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capchine', '0004_auto_20190809_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_code',
            name='accessed_by',
        ),
        migrations.AddField(
            model_name='search_code',
            name='accessed_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='accessed_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
